import { defineStore } from "pinia";

export const recipeStore = defineStore("recipeStore", {
  state: () => ({
    recipes: [
      {
        header: ["High-Protein", "Low-Carb", "Low-Sodium"],
        title: "Beef Cheek Confit With Caramelized Turnips",
        tags: [
          "Sugar-Conscious",
          "Low Sugar",
          "Keto-Friendly",
          "Paleo",
          "Dairy-Free",
          "Gluten-Free",
          "Wheat-Free",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Low Potassium",
          "Paleo",
          "Low Potassium",
          "Blubb",
        ],
        img: "https://www.edamam.com/web-img/deb/debce0693c8d8a6988af80e1f94e4c4c.jpg",
      },
      {
        header: ["High-Protein", "Low-Carb", "Low-Sodium"],
        title: "Beef Cheek Confit With Caramelized Turnips",
        tags: [
          "Sugar-Conscious",
          "Low Sugar",
          "Keto-Friendly",
          "Paleo",
          "Dairy-Free",
          "Gluten-Free",
          "Wheat-Free",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Low Potassium",
          "Paleo",
          "Low Potassium",
          "Paleo",
        ],
        img: "https://www.edamam.com/web-img/deb/debce0693c8d8a6988af80e1f94e4c4c.jpg",
      },
      {
        header: ["High-Protein", "Low-Carb", "Low-Sodium"],
        title: "Beef Cheek Confit With Caramelized Turnips",
        tags: [
          "Sugar-Conscious",
          "Low Sugar",
          "Keto-Friendly",
          "Paleo",
          "Dairy-Free",
          "Gluten-Free",
          "Wheat-Free",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Low Potassium",
          "Paleo",
          "Low Potassium",
          "Paleo",
        ],
        img: "https://www.edamam.com/web-img/deb/debce0693c8d8a6988af80e1f94e4c4c.jpg",
      },
      {
        header: ["High-Protein", "Low-Carb", "Low-Sodium"],
        title: "Beef Cheek Confit With Caramelized Turnips",
        tags: [
          "Sugar-Conscious",
          "Low Sugar",
          "Keto-Friendly",
          "Paleo",
          "Dairy-Free",
          "Gluten-Free",
          "Wheat-Free",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Low Potassium",
          "Paleo",
          "Low Potassium",
          "Paleo",
        ],
        img: "https://www.edamam.com/web-img/deb/debce0693c8d8a6988af80e1f94e4c4c.jpg",
      },
      {
        header: ["High-Protein", "Low-Carb", "Low-Sodium"],
        title: "Beef Cheek Confit With Caramelized Turnips",
        tags: [
          "Sugar-Conscious",
          "Low Sugar",
          "Keto-Friendly",
          "Paleo",
          "Dairy-Free",
          "Gluten-Free",
          "Wheat-Free",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Low Potassium",
          "Paleo",
          "Low Potassium",
          "Paleo",
        ],
        img: "https://www.edamam.com/web-img/deb/debce0693c8d8a6988af80e1f94e4c4c.jpg",
      },
      {
        header: ["High-Protein", "Low-Carb", "Low-Sodium"],
        title: "Beef Cheek Confit With Caramelized Turnips",
        tags: [
          "Sugar-Conscious",
          "Low Sugar",
          "Keto-Friendly",
          "Paleo",
          "Dairy-Free",
          "Gluten-Free",
          "Wheat-Free",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Low Potassium",
          "Paleo",
          "Low Potassium",
          "Paleo",
        ],
        img: "https://www.edamam.com/web-img/deb/debce0693c8d8a6988af80e1f94e4c4c.jpg",
      },
      {
        header: ["High-Protein", "Low-Carb", "Low-Sodium"],
        title: "Beef Cheek Confit With Caramelized Turnips",
        tags: [
          "Sugar-Conscious",
          "Low Sugar",
          "Keto-Friendly",
          "Paleo",
          "Dairy-Free",
          "Gluten-Free",
          "Wheat-Free",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Low Potassium",
          "Paleo",
          "Low Potassium",
          "Paleo",
        ],
        img: "https://www.edamam.com/web-img/deb/debce0693c8d8a6988af80e1f94e4c4c.jpg",
      },
    ],
  }),
  getters: {},
  actions: {
    async getRecipes() {},
  },
});
